---
services:
  db2:
    image: mysql
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: pmamysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
  phpmyadmin2:
    image: phpmyadmin
    container_name: pma2
    links:
      - db2
    environment:
      PMA_HOST: db2
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 6969:80
